name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Processor
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run UnitTests
      run: ./NUnit.ConsoleRunner.3.15.0/tools/nunit3-console.exe  /home/runner/work/Processor/Processor/Processor/bin/Debug/net6.0/Processor.dll
